name: 'Setup Node & pnpm'
description: 'Install pnpm, Node.js and dependencies'

runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v6
      with:
        run_install: false
    - name: Set up Node.js
      uses: actions/setup-node@v7
      with:
        node-version-file: '.nvmrc'
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
      env:
        CYPRESS_INSTALL_BINARY: '0'
