version: '3.8'

services:
  maildev:
    image: maildev/maildev
    environment:
      MAILDEV_INCOMING_USER: mailuser
      MAILDEV_INCOMING_PASS: mailpassword
    ports:
      - "1080:1080"
      - "1025:1025"
  db:
    image: postgres:12.14-alpine
    container_name: coop_pg
    environment:
      - POSTGRES_DB=${NEXT_PUBLIC_APP_SLUG}
      - POSTGRES_USER=${NEXT_PUBLIC_APP_SLUG}
      - POSTGRES_PASSWORD=password
    ports:
      - '5433:5432'
    volumes:
      - coop-pgdata:/var/lib/postgresql/data
    networks:
      - coop-network

volumes:
  coop-pgdata:
    name: coop_pgdata

networks:
  coop-network:
    external: false
    name: coop-network

