-- AlterTable
ALTER TABLE "public"."cras_conseiller_numerique_v1" ADD COLUMN     "permanence_adresse" TEXT,
ADD COLUMN     "permanence_code_commune" TEXT,
ADD COLUMN     "permanence_code_postal" TEXT,
ADD COLUMN     "permanence_email" TEXT,
ADD COLUMN     "permanence_est_structure" BOOLEAN,
ADD COLUMN     "permanence_id" TEXT,
ADD COLUMN     "permanence_latitude" DOUBLE PRECISION,
ADD COLUMN     "permanence_longitude" DOUBLE PRECISION,
ADD COLUMN     "permanence_nom_commune" TEXT,
ADD COLUMN     "permanence_nom_enseigne" TEXT,
ADD COLUMN     "permanence_numero_telephone" TEXT,
ADD COLUMN     "permanence_siret" TEXT,
ADD COLUMN     "permanence_site_web" TEXT,
ADD COLUMN     "permanence_structure_code_commune" TEXT,
ADD COLUMN     "permanence_structure_code_departement" TEXT,
ADD COLUMN     "permanence_structure_code_postal" TEXT,
ADD COLUMN     "permanence_structure_code_region" TEXT,
ADD COLUMN     "permanence_structure_id" TEXT,
ADD COLUMN     "permanence_structure_id_pg" INTEGER,
ADD COLUMN     "permanence_structure_nom" TEXT,
ADD COLUMN     "permanence_structure_nom_commune" TEXT,
ADD COLUMN     "permanence_structure_siret" TEXT,
ADD COLUMN     "permanence_structure_statut" TEXT,
ADD COLUMN     "permanence_structure_type" TEXT;
