import type { LieuAReprendre } from './lieu-a-reprendre'

export const lieuAReprendre = (
  champs: Partial<LieuAReprendre> = {},
): LieuAReprendre => ({
  id: 'e4b5f0d4-5a1f-4a5a-9a4e-2e1c9f0b1d2c',
  nom: 'Espace numérique de Reims',
  siret: '13002603200016',
  rna: null,
  adresse: '12 rue de la Paix',
  commune: 'Reims',
  codePostal: '51100',
  codeInsee: '51454',
  complementAdresse: null,
  banId: '51454_7160_00012',
  latitude: 49.25,
  longitude: 4.03,
  telephone: null,
  courriels: [],
  siteWeb: [],
  horaires: null,
  presentationResume: null,
  presentationDetail: null,
  ficheAccesLibre: null,
  priseRdv: null,
  typologies: ['TIERS_LIEUX'],
  services: ['Aide aux démarches administratives'],
  modalitesAcces: [],
  modalitesAccompagnement: [],
  publicsSpecifiquementAdresses: [],
  priseEnChargeSpecifique: [],
  fraisACharge: [],
  itinerance: [],
  dispositifProgrammesNationaux: [],
  formationsLabels: [],
  autresFormationsLabels: [],
  publie: true,
  ...champs,
})
