export {
  computeUserProfile,
  type DispositifPersonne,
  type Franchissement,
  getInscriptionFlow,
  getNextInscriptionStep,
  type InscriptionContexte,
  type InscriptionEtat,
  InscriptionFlowType,
  InscriptionStep,
  isEnCours,
  isNonDemarree,
  isValidee,
  ProfilInscription,
  profilDeLInscription,
  profilDepuisDispositif,
  profilInscriptionLabels,
  profilInscriptionSlugs,
  profilsInscription,
  UserId,
} from './domain'
