-- Retire la copie que la coop tenait de l'identifiant de cartographie nationale.
--
-- L'identifiant appartient à la cartographie et le registre de l'Entrepôt en est le domicile. La
-- coop en gardait un double, posé par le job de réconciliation, et les deux ont dérivé : sur
-- 12 765 lieux appariés, 553 ne s'accordaient plus, dans les deux sens. Les lectures passent
-- désormais par l'inscription au registre, que `main.lieu_inclusion_registre.structure_coop_id`
-- désigne, et cette colonne n'a plus de lecteur.
--
-- DESTRUCTIF : 7 821 valeurs disparaissent. Ce que le registre ne porte pas a été relevé au
-- préalable et exporté en CSV — 337 lieux, avec les tokens manquants, de quoi les reconstituer
-- depuis un export mednum-cli. La requête qui a produit ce relevé a été retirée : l'export
-- conservé hors du dépôt fait foi.
--
-- L'index qui la portait s'en va avec elle : inutile de le nommer, et le nommer
-- exposerait la migration a echouer la ou il aurait deja disparu.
ALTER TABLE "coop"."lieu_inclusion" DROP COLUMN "id_cartographie_nationale";
