---
name: Release

on:
  push:
    branches:
      - 'main'

permissions:
  contents: read

jobs:
  deploy-dev:
    name: Deploy dev
    uses: ./.github/workflows/deploy.reusable.yml
    with:
      environnement: dev
    permissions:
      contents: read
      deployments: write
    secrets: inherit

  deploy-production:
    name: Deploy production
    needs: deploy-dev
    uses: ./.github/workflows/deploy.reusable.yml
    with:
      environnement: main
    permissions:
      contents: read
      deployments: write
    secrets: inherit
